In [28]:
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

# 1st of all I am importing the data

In [29]:
X,y=load_iris(return_X_y=True)

In [30]:
X.shape

(150, 4)

In [31]:
y.shape

(150,)

## Now Dividing the data into 70 /30 train test sample

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.25 )

# Checking How much part of the data has been pushed to training and testing respectively

In [33]:
X_train.shape

(112, 4)

In [34]:
X_test.shape

(38, 4)

In [35]:
y_train.shape

(112,)

In [36]:
y_test.shape

(38,)

# Now feature scaling

In [37]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

## Logistic Regression Model

In [38]:
from sklearn.linear_model import LogisticRegression


logic_model=LogisticRegression()
logic_model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

### hurrah!!your model has been trained!! Now it's time to check it

# Testing the model

In [39]:
y_predict=logic_model.predict(X_test)

In [40]:
y_predict

array([1, 2, 2, 1, 0, 2, 2, 0, 2, 1, 1, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 2,
       2, 0, 0, 1, 2, 2, 0, 2, 2, 2, 0, 2, 0, 1, 1, 0])

In [41]:
y_test

array([1, 1, 2, 1, 0, 2, 2, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 0, 1, 2, 1, 0, 1, 2, 2, 0, 2, 0, 1, 1, 0])

In [42]:
y_compare=np.vstack((y_predict,y_test)).T

In [43]:
y_compare

array([[1, 1],
       [2, 1],
       [2, 2],
       [1, 1],
       [0, 0],
       [2, 2],
       [2, 2],
       [0, 0],
       [2, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [2, 1],
       [0, 0],
       [1, 1],
       [2, 1],
       [2, 2],
       [0, 0],
       [0, 0],
       [1, 1],
       [2, 2],
       [2, 1],
       [0, 0],
       [2, 1],
       [2, 2],
       [2, 2],
       [0, 0],
       [2, 2],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0]])

### Model Evaluation

In [44]:
from sklearn.metrics import accuracy_score
acscore=accuracy_score(y_predict,y_test)

In [45]:
print("Accuracy score: {}%".format(acscore*100))

Accuracy score: 84.21052631578947%
